### ISSUE TITLE
Doc for Building Invizbox for other Platforms

### ISSUE THREAD

**Issue by makefu** [invizbox/invizbox#6]
Hi,

i am trying to build invizbox for the TP-Link WR703 but i am struggeling how to get 'all' packages from this repository to be used in openwrt image builder.

What i have done so far:
- add `src-git invizbox https://github.com/invizbox/invizbox.git` to `openwrt/feeds.conf.default`
- `./scripts/feeds update -a; ./scripts/feeds install -a`

What are the next steps? which packages are required to build a 'vanilla' invizbox?

Thanks and keep up your good work!

makefu

**Comment by invizbox** [comment]
closing this as part of an issue cleanup - reopen if this is still relevant with up to date details.
